#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT_DIR"

LOG_PREFIX="[issue-worker]"
ISSUE_IDENTIFIER="${ISSUE_IDENTIFIER:-}"
ISSUE_SCRIPT_PATH="${ISSUE_SCRIPT_PATH:-}"
IMPLEMENT_FALLBACK_COMMAND="${IMPLEMENT_FALLBACK_COMMAND:-}"
AUTO_GENERATE_ISSUE_SCRIPT="${AUTO_GENERATE_ISSUE_SCRIPT:-false}"
AUTO_GENERATED_ISSUE_SCRIPT_DIR="${AUTO_GENERATED_ISSUE_SCRIPT_DIR:-scripts/automation/issues}"

log() {
    printf "%s %s\n" "$LOG_PREFIX" "$*"
}

fail() {
    printf "%s ERROR: %s\n" "$LOG_PREFIX" "$*" >&2
    exit 1
}

require_issue_context() {
    [ -n "$ISSUE_IDENTIFIER" ] || fail "ISSUE_IDENTIFIER is required."
}

is_truthy() {
    case "$1" in
        true | TRUE | 1 | yes | YES | y | Y) return 0 ;;
        *) return 1 ;;
    esac
}

run_issue_script() {
    local script_path="$1"
    [ -f "$script_path" ] || return 1

    log "Running implementation script: ${script_path}"
    bash "$script_path"
}

generate_issue_script() {
    local generated_script_path="${AUTO_GENERATED_ISSUE_SCRIPT_DIR}/${ISSUE_IDENTIFIER}.sh"
    mkdir -p "$AUTO_GENERATED_ISSUE_SCRIPT_DIR"

    if [ ! -f "$generated_script_path" ]; then
        printf "%s %s\n" "$LOG_PREFIX" "Auto-generating issue script: ${generated_script_path}" >&2
        cat >"$generated_script_path" <<EOF
#!/usr/bin/env bash
set -euo pipefail

# Auto-generated by scripts/automation/issue_worker.sh
# Issue: ${ISSUE_IDENTIFIER}
# Title: ${ISSUE_TITLE:-}
# URL: ${ISSUE_URL:-}

if [ -n "\${IMPLEMENT_FALLBACK_COMMAND:-}" ]; then
    bash -lc "\$IMPLEMENT_FALLBACK_COMMAND"
    exit 0
fi

echo "[issue-worker-generated] No IMPLEMENT_FALLBACK_COMMAND configured." >&2
echo "[issue-worker-generated] Add implementation steps to ${generated_script_path}." >&2
exit 1
EOF
        chmod +x "$generated_script_path"
    fi

    echo "$generated_script_path"
}

main() {
    require_issue_context

    local issue_id_lc candidate_paths=()
    issue_id_lc="$(echo "$ISSUE_IDENTIFIER" | tr '[:upper:]' '[:lower:]')"

    if [ -n "$ISSUE_SCRIPT_PATH" ]; then
        candidate_paths+=("$ISSUE_SCRIPT_PATH")
    fi

    candidate_paths+=(
        "scripts/automation/issues/${ISSUE_IDENTIFIER}.sh"
        "scripts/automation/issues/${issue_id_lc}.sh"
        "scripts/automation/issues/default.sh"
    )

    for candidate in "${candidate_paths[@]}"; do
        if run_issue_script "$candidate"; then
            return 0
        fi
    done

    if is_truthy "$AUTO_GENERATE_ISSUE_SCRIPT"; then
        local generated_script_path
        generated_script_path="$(generate_issue_script)"
        if run_issue_script "$generated_script_path"; then
            return 0
        fi
    fi

    if [ -n "$IMPLEMENT_FALLBACK_COMMAND" ]; then
        log "Running IMPLEMENT_FALLBACK_COMMAND"
        bash -lc "$IMPLEMENT_FALLBACK_COMMAND"
        return 0
    fi

    fail "No issue implementation script found. Add scripts/automation/issues/${ISSUE_IDENTIFIER}.sh or set IMPLEMENT_FALLBACK_COMMAND."
}

main "$@"
