#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT_DIR"

LOG_PREFIX="[issue-worker]"
ISSUE_IDENTIFIER="${ISSUE_IDENTIFIER:-}"
ISSUE_SCRIPT_PATH="${ISSUE_SCRIPT_PATH:-}"
IMPLEMENT_FALLBACK_COMMAND="${IMPLEMENT_FALLBACK_COMMAND:-}"
AUTO_GENERATE_ISSUE_SCRIPT="${AUTO_GENERATE_ISSUE_SCRIPT:-false}"
AUTO_GENERATED_ISSUE_SCRIPT_DIR="${AUTO_GENERATED_ISSUE_SCRIPT_DIR:-scripts/automation/issues}"
AI_GENERATE_ISSUE_SCRIPT="${AI_GENERATE_ISSUE_SCRIPT:-true}"
OPENAI_API_KEY="${OPENAI_API_KEY:-}"
OPENAI_MODEL="${OPENAI_MODEL:-gpt-5}"
OPENAI_API_BASE="${OPENAI_API_BASE:-https://api.openai.com/v1}"

log() {
    printf "%s %s\n" "$LOG_PREFIX" "$*"
}

fail() {
    printf "%s ERROR: %s\n" "$LOG_PREFIX" "$*" >&2
    exit 1
}

require_issue_context() {
    [ -n "$ISSUE_IDENTIFIER" ] || fail "ISSUE_IDENTIFIER is required."
}

is_truthy() {
    case "$1" in
        true | TRUE | 1 | yes | YES | y | Y) return 0 ;;
        *) return 1 ;;
    esac
}

strip_markdown_fence() {
    local text="$1"
    if printf '%s\n' "$text" | head -n1 | grep -q '^```'; then
        printf '%s\n' "$text" | sed '1d;$d'
        return 0
    fi
    printf '%s\n' "$text"
}

run_issue_script() {
    local script_path="$1"
    log "Running implementation script: ${script_path}"
    bash "$script_path"
}

generate_issue_script_with_ai() {
    local generated_script_path="$1"
    local repo_name repo_root_dirs prompt payload response script_body

    command -v curl >/dev/null 2>&1 || fail "curl is required for AI script generation."
    command -v jq >/dev/null 2>&1 || fail "jq is required for AI script generation."

    repo_name="$(basename "$ROOT_DIR")"
    repo_root_dirs="$(find . -maxdepth 2 -mindepth 1 -type d 2>/dev/null | sed -E 's#^\./##' | sort | head -n 80)"
    prompt="$(cat <<EOF
You are Codex generating a bash implementation script for one Linear issue.

Repository: ${repo_name}
Issue Identifier: ${ISSUE_IDENTIFIER}
Issue Title: ${ISSUE_TITLE:-}
Issue URL: ${ISSUE_URL:-}
Issue Description:
${ISSUE_DESCRIPTION:-}

Repository directories (sample):
${repo_root_dirs}

Return only valid bash code, no markdown.
Script requirements:
- Start with '#!/usr/bin/env bash' and 'set -euo pipefail'
- Assume execution from repository root
- Make minimal, concrete code edits for the issue
- Do NOT run git commit/push/pr commands
- Do NOT use interactive commands
- Keep changes deterministic
- If there is not enough context to implement safely, exit non-zero with a clear error message
EOF
)"

    payload="$(jq -cn --arg model "$OPENAI_MODEL" --arg input "$prompt" '{model:$model,input:$input}')"
    response="$(curl -sS "${OPENAI_API_BASE}/responses" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${OPENAI_API_KEY}" \
        --data "$payload")"

    if echo "$response" | jq -e '.error' >/dev/null 2>&1; then
        fail "OpenAI API error: $(echo "$response" | jq -r '.error.message // "unknown error"')"
    fi

    script_body="$(jq -r '
        if (.output_text? != null and .output_text != "") then
            .output_text
        else
            [ .output[]?.content[]? | (.text // .content // "") ] | join("")
        end
    ' <<<"$response")"

    [ -n "$script_body" ] || fail "OpenAI returned empty script output."
    script_body="$(strip_markdown_fence "$script_body")"
    if ! printf '%s\n' "$script_body" | head -n1 | grep -q '^#!/usr/bin/env bash'; then
        script_body="#!/usr/bin/env bash
set -euo pipefail

${script_body}"
    fi

    printf '%s\n' "$script_body" >"$generated_script_path"
    chmod +x "$generated_script_path"
}

generate_issue_script() {
    local generated_script_path="${AUTO_GENERATED_ISSUE_SCRIPT_DIR}/${ISSUE_IDENTIFIER}.sh"
    mkdir -p "$AUTO_GENERATED_ISSUE_SCRIPT_DIR"

    if [ ! -f "$generated_script_path" ]; then
        printf "%s %s\n" "$LOG_PREFIX" "Auto-generating issue script: ${generated_script_path}" >&2
        if is_truthy "$AI_GENERATE_ISSUE_SCRIPT" && [ -n "$OPENAI_API_KEY" ]; then
            generate_issue_script_with_ai "$generated_script_path"
        else
            if is_truthy "$AI_GENERATE_ISSUE_SCRIPT" && [ -z "$OPENAI_API_KEY" ]; then
                printf "%s %s\n" "$LOG_PREFIX" "OPENAI_API_KEY is not set. Falling back to template script generation." >&2
            fi
            cat >"$generated_script_path" <<EOF
#!/usr/bin/env bash
set -euo pipefail

# Auto-generated by scripts/automation/issue_worker.sh
# Issue: ${ISSUE_IDENTIFIER}
# Title: ${ISSUE_TITLE:-}
# URL: ${ISSUE_URL:-}

if [ -n "\${IMPLEMENT_FALLBACK_COMMAND:-}" ]; then
    bash -lc "\$IMPLEMENT_FALLBACK_COMMAND"
    exit 0
fi

echo "[issue-worker-generated] No IMPLEMENT_FALLBACK_COMMAND configured." >&2
echo "[issue-worker-generated] Add implementation steps to ${generated_script_path}." >&2
exit 1
EOF
            chmod +x "$generated_script_path"
        fi
    fi

    echo "$generated_script_path"
}

main() {
    require_issue_context

    local issue_id_lc candidate_paths=()
    issue_id_lc="$(echo "$ISSUE_IDENTIFIER" | tr '[:upper:]' '[:lower:]')"

    if [ -n "$ISSUE_SCRIPT_PATH" ]; then
        candidate_paths+=("$ISSUE_SCRIPT_PATH")
    fi

    candidate_paths+=(
        "scripts/automation/issues/${ISSUE_IDENTIFIER}.sh"
        "scripts/automation/issues/${issue_id_lc}.sh"
        "scripts/automation/issues/default.sh"
    )

    for candidate in "${candidate_paths[@]}"; do
        if [ ! -f "$candidate" ]; then
            continue
        fi
        if run_issue_script "$candidate"; then
            return 0
        fi
        fail "Issue implementation script failed: ${candidate}"
    done

    if is_truthy "$AUTO_GENERATE_ISSUE_SCRIPT"; then
        local generated_script_path
        generated_script_path="$(generate_issue_script)"
        if [ ! -f "$generated_script_path" ]; then
            fail "Auto-generated issue script was not created: ${generated_script_path}"
        fi
        if run_issue_script "$generated_script_path"; then
            return 0
        fi
        fail "Auto-generated issue script failed: ${generated_script_path}"
    fi

    if [ -n "$IMPLEMENT_FALLBACK_COMMAND" ]; then
        log "Running IMPLEMENT_FALLBACK_COMMAND"
        bash -lc "$IMPLEMENT_FALLBACK_COMMAND"
        return 0
    fi

    fail "No issue implementation script found. Add scripts/automation/issues/${ISSUE_IDENTIFIER}.sh or set IMPLEMENT_FALLBACK_COMMAND."
}

main "$@"
