import type { AppThemeColors, ThemeMode } from "@/theme/types";

export const APP_THEMES: Record<ThemeMode, AppThemeColors> = {
    light: {
        isDark: false,
        background: "#e8efff",
        backgroundAlt: "#dbeafe",
        surface: "#ffffff",
        surfaceMuted: "#f1f5f9",
        textPrimary: "#0f172a",
        textSecondary: "#475569",
        textMuted: "#94a3b8",
        border: "#cbd5f5",
        accent: "#1d4ed8",
        accentSoft: "#93c5fd",
        accentContrast: "#ffffff",
        shadow: "#0f172a",
        cardMuted: "#f8fafc",
        success: "#22c55e",
        danger: "#ef4444",
        warning: "#f97316",
        inputBackground: "#f8fafc",
        inputBorder: "#e2e8f0",
        chipBackground: "#e2e8f0",
        chipText: "#0f172a",
        tabIconActive: "#1f2937",
        tabIconInactive: "#9ca3af",
    },
    dark: {
        isDark: true,
        background: "#0f172a",
        backgroundAlt: "#1e293b",
        surface: "#1f2937",
        surfaceMuted: "#273449",
        textPrimary: "#f8fafc",
        textSecondary: "#cbd5f5",
        textMuted: "#94a3b8",
        border: "#334155",
        accent: "#60a5fa",
        accentSoft: "#1d4ed8",
        accentContrast: "#0f172a",
        shadow: "#000000",
        cardMuted: "#334155",
        success: "#4ade80",
        danger: "#f87171",
        warning: "#fb923c",
        inputBackground: "#1e2635",
        inputBorder: "#3f4c61",
        chipBackground: "#334155",
        chipText: "#e2e8f0",
        tabIconActive: "#e2e8f0",
        tabIconInactive: "#64748b",
    },
};
