import type { AppError } from "@/errors/AppError";
import type { StudyModeViewModel } from "@/screens/StudyMode/StudyModeScreen.types";
import type { CollectionRecord } from "@/services/collections/types";
import { WordResult } from "@/services/dictionary/types";
import type { SearchHistoryEntry } from "@/services/searchHistory/types";

export type SearchScreenProps = {
    searchTerm: string;
    hasSearched: boolean;
    onChangeSearchTerm: (text: string) => void;
    onSubmit: () => void;
    loading: boolean;
    error: AppError | null;
    aiAssistError?: AppError | null;
    aiStatusMessage?: string | null;
    result: WordResult | null;
    examplesVisible: boolean;
    onToggleExamples: () => void;
    onToggleFavorite: (word: WordResult) => void;
    isCurrentFavorite: boolean;
    onPlayPronunciation: () => void;
    pronunciationAvailable: boolean;
    pronunciationLoading?: boolean;
    autocompleteSuggestions: string[];
    autocompleteLoading: boolean;
    onSelectAutocomplete: (term: string) => void;
    recentSearches: SearchHistoryEntry[];
    onSelectRecentSearch: (entry: SearchHistoryEntry) => void;
    onClearRecentSearches: () => void;
    onRetry?: () => void;
    onRetryAiAssist?: () => void;
    onRegenerateExamples?: () => void;
    collectionsEnabled: boolean;
    collections: CollectionRecord[];
    currentCollectionId: string | null;
    onAssignCurrentWordToCollection: (collectionId: string | null) => Promise<void>;
    onCreateCollectionForCurrentWord: (name: string) => Promise<string | null>;
    studyEnabled: boolean;
    studyAvailable: boolean;
    studySession: StudyModeViewModel | null;
    onStartStudyMode: (word: WordResult) => void;
    onRetryStudyMode: () => void;
    onRegenerateStudyMode: () => void;
    onCloseStudyMode: () => void;
    onSelectStudyChoice: (value: string) => void;
    onAdvanceStudyCard: () => void;
};
