import type { AppError } from "@/errors/AppError";
import { DictionaryMode, WordResult } from "@/services/dictionary/types";
import { FavoriteWordEntry, MemorizationStatus } from "@/services/favorites/types";
import type { SearchHistoryEntry } from "@/services/searchHistory/types";
import type { ThemeMode } from "@/theme/types";

export type RootTabNavigatorProps = {
    favorites: FavoriteWordEntry[];
    onToggleFavorite: (word: WordResult) => void;
    onUpdateFavoriteStatus: (word: string, status: MemorizationStatus) => void;
    onRemoveFavorite: (word: string) => void;
    searchTerm: string;
    onChangeSearchTerm: (text: string) => void;
    onSubmitSearch: () => void;
    loading: boolean;
    error: AppError | null;
    result: WordResult | null;
    examplesVisible: boolean;
    onToggleExamples: () => void;
    isCurrentFavorite: boolean;
    onPlayPronunciation: () => void;
    pronunciationAvailable: boolean;
    mode: DictionaryMode;
    onModeChange: (mode: DictionaryMode) => void;
    themeMode: ThemeMode;
    onThemeModeChange: (mode: ThemeMode) => void;
    fontScale: number;
    onFontScaleChange: (scale: number) => void;
    recentSearches: SearchHistoryEntry[];
    onSelectRecentSearch: (entry: SearchHistoryEntry) => void;
    onClearRecentSearches: () => void;
    onRetrySearch: () => void;
    userName: string;
    onLogout: () => void;
    canLogout: boolean;
    isGuest: boolean;
    onRequestLogin: () => void;
    onRequestSignUp: () => void;
    onPlayWordAudio: (word: WordResult) => void;
    appVersion: string;
    profileDisplayName: string | null;
    profileUsername: string | null;
    onUpdateProfile: (displayName: string) => Promise<void>;
    onCheckDisplayName: (displayName: string) => Promise<string>;
    onUpdatePassword: (password: string) => Promise<void>;
    onDeleteAccount: () => Promise<void>;
    onExportBackup: () => Promise<void>;
    onImportBackup: () => Promise<void>;
    onShowOnboarding: () => void;
};
